"""
Django settings for captions_hashtags project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os 
from dotenv import load_dotenv # Naya: .env file se variables load karne ke liye

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv() # Naya: Isse aapki GEMINI_API_KEY aur DJANGO_SECRET_KEY load ho jayegi

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&!&_qw^$zq%tx=g(6q+ja8=z&=zlmyn)%8kl05ka!4@_h$2fuq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'generator',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'captions_hashtags.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Path ko theek kiya gaya hai
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'captions_hashtags.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
    # '/var/www/static/', # Is line ko hata diya gaya hai, local development mein zaroori nahi hai
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Naya: Gemini API Key variable (Yeh key 'generator/ai_logic.py' mein use hogi)
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY and DEBUG:
    print("\n\n--- ⚠️ WARNING: GEMINI_API_KEY is not set in your .env file! AI functions will fail. ---")
    print("--- Please create .env file (near manage.py) and add: GEMINI_API_KEY=\"YOUR_KEY\" ---\n\n")

SOCIAL_LINKS = {
    "linkedin_1": "https://www.linkedin.com/in/abdul-qadir-khan-55a561283?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    "linkedin_2": "https://in.linkedin.com/in/gargi-patel-b6865a368",
    "linkedin_3": "https://www.linkedin.com/in/shreyansh-chaudhary-749139354?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    "linkedin_4": "https://www.linkedin.com/in/aneekaa-sharma-19b3a72b5?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
}

TEMPLATES[0]["OPTIONS"]["context_processors"].append(
    "generator.context_processors.social_links"
)

ALLOWED_HOSTS = [
    'ai-caption-generator-bmpo.onrender.com',
    'localhost',
 '127.0.0.1'
]


